name: Deploy to Docker Hub

on:
  push:
    branches: [ "docker" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build . -t shiva0909/node20:latest

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u shiva0909 --password-stdin

    - name: Push Docker Image
      run: docker push shiva0909/node20:latest